version: '3.9'
services:
  playwright-tests:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/sites-available/default